spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lucian_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

logging:
  level:
    com:
      lucian:
        blog:
          front:
            mapper: debug

mybatis:
  mapper-locations: classpath:front/mapper/*.xml
